
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Frame frame2;

	private global::Gtk.Alignment alignment1;

	private global::Gtk.VPaned vpaned1;

	private global::Gtk.VBox vbox6;

	private global::Gtk.VBox vbox8;

	private global::Gtk.Entry entry_num;

	private global::Gtk.Button button_send_code;

	private global::Gtk.Entry entry_code;

	private global::Gtk.VBox vbox10;

	private global::Gtk.Button button_login;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.TextView statusview;

	private global::Gtk.Entry entry_where;

	private global::Gtk.VBox vbox12;

	private global::Gtk.HBox hbox1;

	private global::Gtk.Button turbo;

	private global::Gtk.Button simple;

	private global::Gtk.HScale hscale_count;

	private global::Gtk.Button button_hunt;

	private global::Gtk.Label GtkLabel3;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.frame2 = new global::Gtk.Frame();
		this.frame2.Name = "frame2";
		this.frame2.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame2.Gtk.Container+ContainerChild
		this.alignment1 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
		this.alignment1.Name = "alignment1";
		// Container child alignment1.Gtk.Container+ContainerChild
		this.vpaned1 = new global::Gtk.VPaned();
		this.vpaned1.CanFocus = true;
		this.vpaned1.Name = "vpaned1";
		this.vpaned1.Position = 10;
		// Container child vpaned1.Gtk.Paned+PanedChild
		this.vbox6 = new global::Gtk.VBox();
		this.vbox6.Name = "vbox6";
		this.vbox6.Spacing = 6;
		// Container child vbox6.Gtk.Box+BoxChild
		this.vbox8 = new global::Gtk.VBox();
		this.vbox8.Name = "vbox8";
		this.vbox8.Spacing = 6;
		// Container child vbox8.Gtk.Box+BoxChild
		this.entry_num = new global::Gtk.Entry();
		this.entry_num.CanFocus = true;
		this.entry_num.Name = "entry_num";
		this.entry_num.IsEditable = true;
		this.entry_num.InvisibleChar = '●';
		this.vbox8.Add(this.entry_num);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.entry_num]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox8.Gtk.Box+BoxChild
		this.button_send_code = new global::Gtk.Button();
		this.button_send_code.CanFocus = true;
		this.button_send_code.Name = "button_send_code";
		this.button_send_code.UseUnderline = true;
		this.button_send_code.Label = global::Mono.Unix.Catalog.GetString("Send tg Code");
		this.vbox8.Add(this.button_send_code);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.button_send_code]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox8.Gtk.Box+BoxChild
		this.entry_code = new global::Gtk.Entry();
		this.entry_code.CanFocus = true;
		this.entry_code.Name = "entry_code";
		this.entry_code.IsEditable = true;
		this.entry_code.InvisibleChar = '●';
		this.vbox8.Add(this.entry_code);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.entry_code]));
		w3.Position = 2;
		w3.Expand = false;
		w3.Fill = false;
		this.vbox6.Add(this.vbox8);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.vbox8]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.vbox10 = new global::Gtk.VBox();
		this.vbox10.Name = "vbox10";
		this.vbox10.Spacing = 6;
		// Container child vbox10.Gtk.Box+BoxChild
		this.button_login = new global::Gtk.Button();
		this.button_login.CanFocus = true;
		this.button_login.Name = "button_login";
		this.button_login.UseUnderline = true;
		this.button_login.Label = global::Mono.Unix.Catalog.GetString("Login");
		this.vbox10.Add(this.button_login);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.button_login]));
		w5.Position = 0;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox10.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.statusview = new global::Gtk.TextView();
		this.statusview.CanFocus = true;
		this.statusview.Name = "statusview";
		this.statusview.Editable = false;
		this.GtkScrolledWindow.Add(this.statusview);
		this.vbox10.Add(this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.GtkScrolledWindow]));
		w7.Position = 1;
		// Container child vbox10.Gtk.Box+BoxChild
		this.entry_where = new global::Gtk.Entry();
		this.entry_where.CanFocus = true;
		this.entry_where.Name = "entry_where";
		this.entry_where.IsEditable = true;
		this.entry_where.InvisibleChar = '●';
		this.vbox10.Add(this.entry_where);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.entry_where]));
		w8.Position = 2;
		w8.Expand = false;
		w8.Fill = false;
		this.vbox6.Add(this.vbox10);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.vbox10]));
		w9.Position = 1;
		// Container child vbox6.Gtk.Box+BoxChild
		this.vbox12 = new global::Gtk.VBox();
		this.vbox12.Name = "vbox12";
		this.vbox12.Spacing = 6;
		// Container child vbox12.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.turbo = new global::Gtk.Button();
		this.turbo.CanFocus = true;
		this.turbo.Name = "turbo";
		this.turbo.UseUnderline = true;
		this.turbo.Label = global::Mono.Unix.Catalog.GetString("turbo");
		this.hbox1.Add(this.turbo);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.turbo]));
		w10.Position = 0;
		w10.Expand = false;
		w10.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.simple = new global::Gtk.Button();
		this.simple.CanFocus = true;
		this.simple.Name = "simple";
		this.simple.UseUnderline = true;
		this.simple.Label = global::Mono.Unix.Catalog.GetString("simple");
		this.hbox1.Add(this.simple);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.simple]));
		w11.Position = 2;
		w11.Expand = false;
		w11.Fill = false;
		this.vbox12.Add(this.hbox1);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox12[this.hbox1]));
		w12.Position = 0;
		w12.Expand = false;
		w12.Fill = false;
		// Container child vbox12.Gtk.Box+BoxChild
		this.hscale_count = new global::Gtk.HScale(null);
		this.hscale_count.CanFocus = true;
		this.hscale_count.Name = "hscale_count";
		this.hscale_count.Adjustment.Lower = 1D;
		this.hscale_count.Adjustment.Upper = 100D;
		this.hscale_count.Adjustment.PageIncrement = 10D;
		this.hscale_count.Adjustment.StepIncrement = 1D;
		this.hscale_count.Adjustment.Value = 50D;
		this.hscale_count.DrawValue = true;
		this.hscale_count.Digits = 0;
		this.hscale_count.ValuePos = ((global::Gtk.PositionType)(2));
		this.vbox12.Add(this.hscale_count);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox12[this.hscale_count]));
		w13.Position = 1;
		w13.Expand = false;
		w13.Fill = false;
		// Container child vbox12.Gtk.Box+BoxChild
		this.button_hunt = new global::Gtk.Button();
		this.button_hunt.CanFocus = true;
		this.button_hunt.Name = "button_hunt";
		this.button_hunt.UseUnderline = true;
		this.button_hunt.Label = global::Mono.Unix.Catalog.GetString("Hunt!");
		this.vbox12.Add(this.button_hunt);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox12[this.button_hunt]));
		w14.Position = 2;
		w14.Expand = false;
		w14.Fill = false;
		this.vbox6.Add(this.vbox12);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.vbox12]));
		w15.Position = 2;
		w15.Expand = false;
		w15.Fill = false;
		this.vpaned1.Add(this.vbox6);
		this.alignment1.Add(this.vpaned1);
		this.frame2.Add(this.alignment1);
		this.GtkLabel3 = new global::Gtk.Label();
		this.GtkLabel3.Name = "GtkLabel3";
		this.GtkLabel3.LabelProp = global::Mono.Unix.Catalog.GetString("<b>GtkFrame</b>");
		this.GtkLabel3.UseMarkup = true;
		this.frame2.LabelWidget = this.GtkLabel3;
		this.Add(this.frame2);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 396;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.button_send_code.Clicked += new global::System.EventHandler(this.OnButtonSendCodeClicked);
		this.button_login.Clicked += new global::System.EventHandler(this.OnButtonLoginClicked);
		this.turbo.Clicked += new global::System.EventHandler(this.OnTurboClicked);
		this.simple.Clicked += new global::System.EventHandler(this.OnSimpleClicked);
		this.button_hunt.Clicked += new global::System.EventHandler(this.OnButtonHuntClicked);
	}
}
